const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const {pathToFileURL} = require('node:url');
const {chromium} = require('playwright');
const root = path.resolve(__dirname, '..');
const docs = path.join(root, 'docs');
const catalog = JSON.parse(fs.readFileSync(path.join(root, 'library.json'), 'utf8'));
const out = path.join(root, 'qa');
fs.mkdirSync(out, {recursive:true});
const types = {'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.jpg':'image/jpeg'};
const server = http.createServer((req,res) => {
  const url = new URL(req.url, 'http://localhost');
  const relative = decodeURIComponent(url.pathname).replace(/^\/ceibs-note\//, '');
  const file = path.resolve(docs, relative || 'index.html');
  if (!file.startsWith(docs + path.sep) || !fs.existsSync(file) || !fs.statSync(file).isFile()) { res.writeHead(404).end(); return; }
  res.setHeader('Content-Type', types[path.extname(file)] || 'application/octet-stream');
  fs.createReadStream(file).pipe(res);
});

(async () => {
  let browser;
  try {
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
    const base = `http://127.0.0.1:${server.address().port}/ceibs-note/`;
    browser = await chromium.launch({headless:true, ...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {})});
    const context = await browser.newContext({viewport:{width:1440,height:1050}});
    const page = await context.newPage();
    const errors = [], missing = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', r => { if (r.url().startsWith(base) && r.status() >= 400) missing.push(r.url()); });
    const cards = () => page.locator('.page-card');
    const overflow = async () => assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth + 1), false, 'Horizontal overflow');
    await page.goto(base);
    await page.locator('.page-card').first().waitFor();
    assert.equal(await cards().count(), catalog.pages.length);
    await page.locator('.page-card').last().scrollIntoViewIfNeeded();
    await page.waitForFunction(() => [...document.querySelectorAll('.page-preview img')].every(i => i.complete && i.naturalWidth > 0));
    await page.evaluate(() => scrollTo(0,0));
    await page.screenshot({path:path.join(out, 'desktop.png'),fullPage:true});
    await overflow();
    await page.locator('#topics [data-topic="competitions"]').click();
    assert.equal(await cards().count(), 2, 'Parent topic includes nested pages');
    await page.locator('#topics [data-topic="innovatechina"]').click();
    assert.equal(await cards().count(), 1);
    await page.reload();
    assert.equal(await page.locator('#heading').textContent(), 'INNOVATEChina');
    await page.locator('.primary-nav [data-view="all"]').click();
    await page.locator('#search').fill('A/B testing');
    assert.equal(await cards().count(), 1);
    assert.equal(await cards().first().getAttribute('data-id'), 'yelp-experimentation');
    await page.locator('#clear-search').click();
    await page.locator('[data-format="Interactive"]').click();
    assert.equal(await cards().count(), 1);
    await page.locator('[data-format="Website"]').click();
    assert.equal(await cards().count(), 0);
    assert.equal(await page.locator('#empty-state').isVisible(), true);
    await page.locator('#empty-reset').click();
    await page.locator('[data-save="microeconomics-quiz"]').click();
    await page.locator('.primary-nav [data-view="saved"]').click();
    assert.equal(await cards().count(), 1);
    await page.reload();
    assert.equal(await cards().count(), 1, 'Bookmark survives reload');
    await page.locator('.card-body h2 a').click();
    const quiz = page.frameLocator('#reader-frame');
    await quiz.locator('.question-meta .id').waitFor();
    assert.equal(await quiz.locator('.question-meta .id').textContent(), 'INTRO-01');
    await quiz.locator('input[name="answer"]').first().check();
    await quiz.getByRole('button', {name:'Check answer',exact:true}).click();
    await quiz.locator('#solution').waitFor();
    await page.reload();
    await quiz.locator('#solution').waitFor();
    await page.screenshot({path:path.join(out,'reader-desktop.png'),fullPage:true});
    await page.locator('#back-library').click();
    assert.equal(await page.locator('#heading').textContent(), 'Saved pages');
    await page.locator('.primary-nav [data-view="recent"]').click();
    assert.equal(await cards().count(), 1);
    await page.locator('.primary-nav [data-view="all"]').click();
    await page.locator('#sort').selectOption('title');
    const titles = await page.locator('.card-body h2').allTextContents();
    assert.deepEqual(titles, [...titles].sort((a,b) => a.localeCompare(b)));
    for (const width of [1920,1024,768,390,320]) {
      await page.setViewportSize({width,height:900});
      await page.locator('#grid-view').click();
      await overflow();
      if (width === 390) await page.screenshot({path:path.join(out,'mobile.png'),fullPage:true});
      await page.locator('#list-view').click();
      await overflow();
    }
    await page.locator('#open-menu').click();
    assert.equal(await page.locator('.workspace').evaluate(el => el.inert), true);
    await page.locator('#topics [data-topic="economics"]').click();
    assert.equal(await page.locator('#sidebar').isVisible(), false);
    assert.equal(await page.locator('.workspace').evaluate(el => el.inert), false);
    await page.locator('.card-body h2 a').click();
    await quiz.locator('.question-meta .id').waitFor();
    await overflow();
    await page.screenshot({path:path.join(out,'reader-mobile.png'),fullPage:true});
    await page.setViewportSize({width:1440,height:1000});
    for (const entry of catalog.pages) {
      await page.goto(base + 'reader.html?id=' + entry.id);
      await page.frameLocator('#reader-frame').locator('body').waitFor();
      assert.equal(await page.locator('#reader-title').textContent(), entry.title);
      assert.ok((await page.frameLocator('#reader-frame').locator('body').innerText()).length > 100);
    }
    await page.goto(base + 'reader.html?id=missing');
    assert.equal(await page.locator('#reader-error').isVisible(),true);
    assert.equal(await page.locator('#reader-frame').isVisible(),false);
    const offline = await browser.newContext({offline:true});
    const local = await offline.newPage();
    await local.goto(pathToFileURL(path.join(docs,'index.html')).href);
    assert.equal(await local.locator('.page-card').count(),catalog.pages.length,'File preview works offline');
    await local.locator('[data-id="microeconomics-quiz"] h2 a').click();
    await local.frameLocator('#reader-frame').locator('.question-meta .id').waitFor();
    await context.addInitScript(() => Object.defineProperty(window,'localStorage',{get(){throw new Error('Blocked');}}));
    await page.goto(base);
    await page.locator('[data-save="microeconomics-quiz"]').click();
    await page.locator('.primary-nav [data-view="saved"]').click();
    assert.equal(await cards().count(),1,'Library works with blocked storage');
    assert.deepEqual(errors,[],'No browser errors');
    assert.deepEqual(missing,[],'No missing local resources');
    console.log('PASS: topic hierarchy, search, formats, bookmarks, reader, quiz persistence, sorting, grid/list, mobile menu, offline files, blocked storage, and all page links.');
    console.log('Screenshots:',out);
  } finally {
    if (browser) await browser.close();
    await new Promise(resolve => server.close(resolve));
  }
})().catch(error => {console.error(error); process.exitCode = 1;});
